"""
Amelia Shengaout
CSC 6210 Computer Architecture
Spring 2026
Hardware/control_unit.py — Control Unit: instruction decode → control signals
"""

from dataclasses import dataclass

# ── Function codes (funct field, bits [5:0]) ──────────────────────────────────
# Encoded in the function field (not the opcode) per spec Section 1.4
FUNCT_AND     = 0b100100   # 0x24  standard AND
FUNCT_OR      = 0b100101   # 0x25  standard OR
FUNCT_AND_NOT = 0b100110   # 0x26  AND with inversion of source A (NOT via control signal)

_FUNCT_NAMES = {
    FUNCT_AND:     "AND    (100100)",
    FUNCT_OR:      "OR     (100101)",
    FUNCT_AND_NOT: "AND-NOT(100110)",
}


@dataclass
class ControlSignals:
    """All control signals generated by the control unit for one instruction."""
    alu_op:     str   # "AND" or "OR"
    invert:     bool  # True → ALU must invert source-A before operating
    reg_write:  bool  # True → write ALU result back to rd


@dataclass
class DecodedInstruction:
    """Fields extracted from a 32-bit R-type instruction word."""
    opcode:  int
    rs:      int
    rt:      int
    rd:      int
    shamt:   int
    funct:   int
    signals: ControlSignals


class ControlUnit:
    """Decodes a 32-bit R-type instruction and generates control signals.

    Instruction format (MIPS R-type):
      [31:26] opcode — must be 0 (R-type)
      [25:21] rs     — source register 1
      [20:16] rt     — source register 2
      [15:11] rd     — destination register
      [10:6]  shamt  — shift amount (unused; must be 0)
      [5:0]   funct  — selects AND / OR / AND-NOT

    The inversion flag is *encoded in funct* (not opcode), satisfying
    spec Section 1.4 and Section 3.3.
    """

    def decode(self, instruction_word: int) -> DecodedInstruction:
        opcode = (instruction_word >> 26) & 0x3F
        rs     = (instruction_word >> 21) & 0x1F
        rt     = (instruction_word >> 16) & 0x1F
        rd     = (instruction_word >> 11) & 0x1F
        shamt  = (instruction_word >>  6) & 0x1F
        funct  =  instruction_word        & 0x3F

        if opcode != 0:
            raise ValueError(
                f"Unsupported opcode 0x{opcode:02X}. "
                "Only R-type (opcode=0) instructions are supported."
            )

        if funct == FUNCT_AND:
            signals = ControlSignals(alu_op="AND", invert=False, reg_write=True)
        elif funct == FUNCT_OR:
            signals = ControlSignals(alu_op="OR",  invert=False, reg_write=True)
        elif funct == FUNCT_AND_NOT:
            # invert=True tells the ALU to complement source-A before ANDing
            signals = ControlSignals(alu_op="AND", invert=True,  reg_write=True)
        else:
            raise ValueError(
                f"Unsupported funct 0x{funct:02X}. "
                "Supported: AND(0x24), OR(0x25), AND-NOT(0x26)."
            )

        return DecodedInstruction(opcode, rs, rt, rd, shamt, funct, signals)

    @staticmethod
    def funct_name(funct: int) -> str:
        return _FUNCT_NAMES.get(funct, f"UNKNOWN(0x{funct:02X})")
